behaviors:
  CannonTraining:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 6.88e-6
      beta: 0.003444
      epsilon: 0.1688
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true

environment_parameters:
  enemy_speed:
    curriculum:
      - name: Lesson0 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: CannonTraining
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 2.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: CannonTraining
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 2.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: CannonTraining
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 2.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 3.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: CannonTraining
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 2.5
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 4.0
      - name: Lesson4
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 5.0
engine_settings:
  time_scale: 20
  no_graphics: true