behaviors:
  ShipTraining:
    trainer_type: sac
    threaded: true
    hyperparameters:
      buffer_init_steps: 1000
      batch_size: 1024
      buffer_size: 100000
      learning_rate: 0.0002
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
        network_settings:
          goal_conditioning_type: none
          num_layers: 0
    behavioral_cloning:
      strength: 0.5
      demo_path: Assets\AimbotRecMovement.demo
    keep_checkpoints: 5
    max_steps: 700000
    time_horizon: 1000
    summary_freq: 20000

