behaviors:
  ShipTraining:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.0002
      beta: 0.003
      epsilon: 0.15
      lambd: 0.93
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: fully_connected
      conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    behavioral_cloning:
      strength: 0.5
      demo_path: Assets\AimbotRecMovement.demo
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 1000
    summary_freq: 20000
engine_settings:
  width: 1800
  height: 1600
  quality_level: 3
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
