behaviors:
  ShipTraining:
    trainer_type:   sac
    hyperparameters:    
      learning_rate:    0.0003
      learning_rate_schedule:   constant
      batch_size:   512
      buffer_size:  58000
      tau:  0.005
      save_replay_buffer:   False
      init_entcoef: 0.5
    network_settings:   
      normalize:    true
      hidden_units: 512
      num_layers:   3
      vis_encode_type: simple
      goal_conditioning_type:   none
    reward_signals: 
      extrinsic:    
        gamma:  0.99
        strength:   1.0
        network_settings:   
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: none
      gail: 
        gamma: 0.99
        strength: 0.25
        network_settings:   
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type:   none  
        learning_rate:  0.0003
        use_actions: true
        use_vail: false
        demo_path: Demos\AimbotNoRay.demo
    behavioral_cloning:
      strength: 0.4
      demo_path: Demos\AimbotNoRay.demo
      steps: 80000
    keep_checkpoints: 5
    max_steps:  2000000
    time_horizon: 256
    summary_freq: 10000
    threaded: true
engine_settings:
  width: 1000
  height: 700
  quality_level: 0
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false